---
- name: Clone MMC
  import_playbook: clone_mmc.yml
- name: Clone cassandra
  import_playbook: clone_cassandra.yml
- name: Clone msvinserter
  import_playbook: clone_msvinserter.yml

- name: Create seachange user
  hosts: all
  tasks:
    user:
      name: seachange
      shell: /bin/bash
      group: seachange
      groups: wheel
      password: 6$Hzk15seL$kLMMGPrF7o4TD7cYd3iA1siR.fhGl0nSoAiGj8GWbs2ZmUgFGhRzY5xL82NZEe89UR68je7DzX4A91x1qWj0C.
      append: yes


- name: Deploy MMC
  hosts: mmc
  vars:
    - linux_password: SeaChange
  gather_facts: true
  vars_files:
    - mmc/vars/main.yml
  roles:
    - { role: mmc, tags: mmc }
