---
- name: Clone MMC
  import_playbook: clone_mmc.yml
- name: Clone cassandra
  import_playbook: clone_cassandra.yml
- name: Clone msvinserter
  import_playbook: clone_msvinserter.yml
# - name: create inventory
#   import_playbook: create_inventory.yml
#   tags: inventory

- name: Create user and set NTP
  hosts: all
  become: True

  roles:
- { role: "nickjj.user", tags: "user", user_name: "seachange", user_groups: [ wheel, seachange ] }
- { role: "geerlingguy.ntp", tags: "ntp" }

- name: Deploy MMC
  hosts: mmc
  vars:
    - linux_password: SeaChange
  gather_facts: true
  vars_files:
    - mmc/vars/main.yml
  roles:
    - { role: mmc, tags: mmc }
